required = [
  "github.com/go-chi/chi"
  , "github.com/grpc-ecosystem/go-grpc-middleware"
  , "github.com/lyft/protoc-gen-validate"
  , "github.com/pkg/errors"
  , "github.com/rs/cors"
  , "github.com/shurcooL/vfsgen"
  , "google.golang.org/genproto"
]

[prune]
  go-tests = true

[[constraint]]
  name = "github.com/bdlm/log"
  version = "^0.1"

[[override]]
  branch = "master"
  name = "github.com/golang/protobuf"
  #version = "^1.2.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "^1.5.1"

[[constraint]]
  name = "github.com/lyft/protoc-gen-validate"
  branch = "master"

[[constraint]]
  name = "github.com/shurcooL/vfsgen"
  branch = "master"

[[constraint]]
  name = "google.golang.org/genproto"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.16.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "^1.3"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "^3.3"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  branch = "master"

[[constraint]]
  name = "github.com/rs/cors"
  version = "^1.3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8"
